name: Soledad Vega
favicon: null
layout_spectrum: 0.29810386383906007
typography_spectrum: 0.8434171602129936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8419637745246291
  lightness: 0.5808462195564061
  saturation: 0.7960253187920898
  rhythmicContrast: 0.4095494656357914
purpose: []
