name: Soledad Vega
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf0e7'
    - '#010101'
    - '#fa8279'
    - '#c33b5f'
    - '#b4b3b2'
  brandStrength: 0.8419637745246291
  lightness: 0.5808462195564061
  saturation: 0.7960253187920898
  rhythmicContrast: 0.4095494656357914
purpose: []
